all: coordinate 
clean:
	rm -f coordinate *.o
.PHONY: all clean

CXX = g++
CPPFLAGS =
CXXFLAGS = -std=c++11 -Wall -Wextra -g
LIBS = -lGL -lGLU -lGLEW -lglad -lglfw3 -lX11 -lXxf86vm -lXrandr -pthread -lXi -ldl -lXcursor -lXinerama
LDFLAGS =

coordinate: coordinate.o
	$(CXX) $(LDFLAGS) -o coordinate coordinate.o $(LIBS)
